benchmarks/gem_busy: Fix compile error
The benchmark was failing with:
gem_busy.c:158:8: error: implicit declaration of function 'intel_gen'
is invalid in C99 [-Werror,-Wimplicit-function-declaration]
gen = intel_gen(intel_get_drm_devid(fd));

The root cause was due to the local lib directory not being specified
in benchmarks/Android.mk, resulting in intel_chipset.h from drm being
used instead.

This patch adds the lib path to the LOCAL_C_INCLUDES

Signed-off-by: Derek Morton <derek.j.morton@intel.com>
Signed-off-by: Marius Vlad <marius.c.vlad@intel.com>